version: 2
jobs:
  build:
    docker:
      - image: unitedincome/std:latest
        auth:
          username: unitedincome
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "./package.json" }}

      - run:
          name: Installing Dependencies
          command:
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
            yarn install

      - save_cache:
          paths:
            - ~/project/node_modules
          key: v2-dependencies-{{ checksum "./package.json" }}

      - run:
          name: Linting Build
          command: yarn lint

      - run:
          name: Running Tests
          command: yarn test

      - run:
          name: Build package
          command: yarn build

      - run:
          name: Configure Git
          command: |
            git config user.email "engineering@unitedincome.com"
            git config user.name "United Income Engineering"

      - deploy:
          name: Publish to NPM
          command: |
            if [ "${CIRCLE_BRANCH}" == "v1.1" ]; then
              npm version patch -m "Bumping up version to %s [skip ci]"
              npm publish
              git push --set-upstream origin $CIRCLE_BRANCH
            fi
