name: visual-tests
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run Percy Tests
        uses: percy/storybook-action@v0.1.1
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          PERCY_TARGET_BRANCH: ${{ secrets.PERCY_TARGET_BRANCH }}
          PERCY_TARGET_COMMIT: ${{ secret.PERCY_TARGET_COMMIT }}